/**
 * Trace Serializer - Constructs and appends Agent Trace records
 * Implements the Agent Trace specification for intent-code traceability
 */

import * as fs from "fs/promises"
import * as path from "path"
import { v4 as uuidv4 } from "uuid"
import { AgentTraceRecord, AgentTraceFile, AgentTraceConversation, AgentTraceRange } from "./types"

export class TraceSerializer {
	private workspaceRoot: string
	private orchestrationDir: string

	constructor(workspaceRoot: string) {
		this.workspaceRoot = workspaceRoot
		this.orchestrationDir = path.join(workspaceRoot, ".orchestration")
	}

	/**
	 * Create and append a trace record to agent_trace.jsonl
	 * @param params Trace record parameters
	 */
	async appendTrace(params: {
		sessionId: string
		intentId: string
		filePath: string
		startLine: number
		endLine: number
		contentHash: string
		modelIdentifier: string
		mutationClass: "AST_REFACTOR" | "INTENT_EVOLUTION" | "BUG_FIX"
		ranges?: Array<{ start_line: number; end_line: number; content_hash: string }>
	}): Promise<string> {
		const traceId = uuidv4()
		const timestamp = new Date().toISOString()

		// Get git revision if available
		const gitRevision = await this.getGitRevision()

		// Convert to relative path
		const relativePath = path.relative(this.workspaceRoot, params.filePath).replace(/\\/g, "/")

		// Support AST-level ranges for precise correlation
		const ranges = params.ranges || [
			{
				start_line: params.startLine,
				end_line: params.endLine,
				content_hash: params.contentHash,
			},
		]

		const conversation: AgentTraceConversation = {
			url: params.sessionId,
			contributor: {
				entity_type: "AI",
				model_identifier: params.modelIdentifier,
			},
			ranges,
			related: [
				{
					type: "specification",
					value: params.intentId,
				},
			],
		}

		const file: AgentTraceFile = {
			relative_path: relativePath,
			conversations: [conversation],
		}

		const record: AgentTraceRecord = {
			id: traceId,
			timestamp,
			mutation_class: params.mutationClass,
			vcs: {
				type: "git",
				revision_id: gitRevision,
			},
			session_id: params.sessionId,
			files: [file],
		}

		// Append to JSONL file (one JSON object per line)
		const jsonlPath = path.join(this.orchestrationDir, "agent_trace.jsonl")
		const jsonLine = JSON.stringify(record) + "\n"

		try {
			await fs.appendFile(jsonlPath, jsonLine, "utf8")
		} catch (error) {
			// If file doesn't exist, create it
			await fs.writeFile(jsonlPath, jsonLine, "utf8")
		}

		return traceId
	}

	/**
	 * Read all trace records from agent_trace.jsonl
	 * @returns Array of trace records
	 */
	async readTraces(): Promise<AgentTraceRecord[]> {
		try {
			const jsonlPath = path.join(this.orchestrationDir, "agent_trace.jsonl")
			const content = await fs.readFile(jsonlPath, "utf8")

			const lines = content.trim().split("\n")
			return lines.filter((line) => line.trim()).map((line) => JSON.parse(line) as AgentTraceRecord)
		} catch {
			return []
		}
	}

	/**
	 * Get traces for a specific intent
	 * @param intentId The intent ID
	 * @returns Array of trace records
	 */
	async getTracesForIntent(intentId: string): Promise<AgentTraceRecord[]> {
		const allTraces = await this.readTraces()

		return allTraces.filter((trace) => {
			return trace.files.some((file) => {
				return file.conversations.some((conv) => {
					return conv.related.some((rel) => rel.type === "specification" && rel.value === intentId)
				})
			})
		})
	}

	/**
	 * Get traces for a specific file
	 * @param filePath Absolute or relative file path
	 * @returns Array of trace records
	 */
	async getTracesForFile(filePath: string): Promise<AgentTraceRecord[]> {
		const allTraces = await this.readTraces()
		const relativePath = path.relative(this.workspaceRoot, filePath).replace(/\\/g, "/")

		return allTraces.filter((trace) => {
			return trace.files.some((file) => file.relative_path === relativePath)
		})
	}

	/**
	 * Update intent_map.md with new trace entry (incremental, deduplicated by file)
	 */
	async updateIntentMap(intentId: string, filePath: string, contentHash: string, traceId: string): Promise<void> {
		const mapPath = path.join(this.orchestrationDir, "intent_map.md")
		const relativePath = path.relative(this.workspaceRoot, filePath).replace(/\\/g, "/")
		const timestamp = new Date().toISOString()
		const hashShort = contentHash.substring(0, 16) + "..."
		const traceShort = traceId.substring(0, 8)
		const newRow = `| \`${relativePath}\` | - | \`${hashShort}\` | \`${timestamp}\` | \`${traceShort}\` |`

		let content: string
		try {
			content = await fs.readFile(mapPath, "utf8")
		} catch {
			content = "# Intent Spatial Map\n\n_Auto-generated by HookEngine PostToolUse. Do not edit manually._\n\n"
		}

		// Find our intent section (## INTENT_ID or ## INTENT_ID: Name)
		const intentSectionStart = content.indexOf(`## ${intentId}`)
		if (intentSectionStart === -1) {
			// Append new intent section
			const section = `\n## ${intentId}\n\n| File | AST Anchor | Last Content Hash | Last Modified | Trace ID |\n|------|------------|-------------------|---------------|----------|\n${newRow}\n`
			await fs.appendFile(mapPath, section, "utf8")
			return
		}

		// Find table body (after header row and separator)
		const tableStart = content.indexOf("| File |", intentSectionStart)
		if (tableStart === -1) {
			await fs.appendFile(mapPath, `\n${newRow}\n`, "utf8")
			return
		}

		const sepEnd = content.indexOf("\n", content.indexOf("\n", tableStart) + 1)
		const tableBodyStart = sepEnd + 1
		const nextSection = content.indexOf("\n## ", tableBodyStart)
		const tableBodyEnd = nextSection === -1 ? content.length : nextSection
		const tableBody = content.slice(tableBodyStart, tableBodyEnd)

		// Check if we already have this file
		const filePattern = relativePath.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
		const fileRowRegex = new RegExp(`\\|[^|]*\`${filePattern}\`[^|]*\\|[^\\n]+`, "g")
		let newTableBody: string
		if (fileRowRegex.test(tableBody)) {
			newTableBody = tableBody.replace(fileRowRegex, newRow)
		} else {
			newTableBody = tableBody.trimEnd() + (tableBody.endsWith("\n") ? "" : "\n") + newRow + "\n"
		}

		const before = content.slice(0, tableBodyStart)
		const after = content.slice(tableBodyEnd)
		await fs.writeFile(mapPath, before + newTableBody + after, "utf8")
	}

	/**
	 * Get current git revision
	 * @returns Git SHA or "unknown"
	 */
	private async getGitRevision(): Promise<string> {
		try {
			const { execFile } = await import("child_process")
			const { promisify } = await import("util")
			const execFileAsync = promisify(execFile)

			const { stdout } = await execFileAsync("git", ["rev-parse", "HEAD"], {
				cwd: this.workspaceRoot,
			})

			return stdout.trim()
		} catch {
			return "unknown"
		}
	}
}
